name: app_suite_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - apps/admin_app
  - apps/partner_app
  - apps/user_app
  - packages/phone_auth
  - packages/core
  - packages/services
  - packages/design_system
